spring:
  redis:
    #连接超时时间（毫秒）
    timeout: 50000
    database: 0
    enable: true
    sysName: capol
    # Redis服务器连接密码（默认为空）
    password: capol2000
    # 连接超时时间（毫秒）
    commandTimeout: 50000
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 5000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 30
        # 连接池中的最小空闲连接
        min-idle: 5
    cluster:
      nodes:
        - 10.1.207.13:7000
        - 10.1.207.13:7001
        - 10.1.207.14:7000
        - 10.1.207.14:7001
        - 10.1.207.15:7000
        - 10.1.207.15:7001
      # 跨集群执行命令时要遵循的最大重定向数量
      max-redirects: 3
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.207.12:3306/db_capol_notify?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
    password: mysql_root_test_2021
    type: com.alibaba.druid.pool.DruidDataSource
    ### 连接池配置
    druid:
      initial-size: 50
      max-active: 200
      min-idle: 50
      max-wait: 50
      validation-query: SELECT 1
  #配置rabbitMq 服务器
  rabbitmq:
    host: 10.1.207.30
    port: 5672
    username: bimAdmin
    password: admin_2020_prod
    #虚拟host (CapolNotifyVHost)可以不设置,使用server默认host
    virtual-host: cooperative_vhost
    publisher-returns: true #开启confirm确认模式
    publisher-confirm-type: correlated

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  global-config:
    # 是否打印 Logo banner
    banner: true
    dbConfig:
      # 逻辑已删除值
      logicDeleteValue: 0
      # 逻辑未删除值
      logicNotDeleteValue: 1
xxl:
  job:
    admin:
      # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: https://qareportjob.capol.cn/xxl-job-admin
      # 执行器通讯TOKEN [选填]：非空时启用
      ussername: admin
      password: 123456
    accessToken:
    executor:
      # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: capol-notify-job-executor
      # 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
      address:
      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip:
      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 9700
      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: D:/logs/jobhandler
      # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能
      logretentiondays: 30

logging:
  level:
    com.baomidou.mybatisplus: DEBUG
    com.capol.notify.manage.domain.repository: DEBUG
  file:
    path: /logs/job

capol:
  jwt:
    issuer: capol
    key: fa6Y!#2zYfdnzD#Z@USNFlQIgMROqR6aNnPeHy%Yw$9eCtOnjt
    expires-hours: 8
  notify:
    retry:
      max-count: 19